---
title: "Post-hoc analyses of adaptation experiment"
author: "Aleeza Yu"
date: "05/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "/Users/sebschu/Dropbox/Uni/RA/adaptation/adaptation/experiments/1_adaptation/analysis/")
```

```{r packages, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(gridExtra)
library(DescTools)
library(splines)
source("helpers.R")
```

```{r data, echo=FALSE}
# Load data

# Might-biased condition
trials.might = read.csv("../data/1_adaptation-might-trials.csv")
exp_trials.might = read.csv("../data/1_adaptation-might-exp_trials.csv")


# Probably-biased condition
trials.probably = read.csv("../data/1_adaptation-probably-trials.csv")
exp_trials.probably = read.csv("../data/1_adaptation-probably-exp_trials.csv")

```

## Analysis 1: No exclusions based on catch-trial performance

### Catch trial performance

```{r catch_trials, echo=FALSE}

get_correct_catch_trial_counts = function (data) {
  ret = data %>% 
  filter(., catch_trial == 1) %>%
  group_by(workerid) %>%
  summarise(catch_perf = sum(catch_trial_answer_correct))
  
  return(ret)
}

EXCLUDE_BELOW = 0

catch_trial_perf.trials.might = get_correct_catch_trial_counts(trials.might)
catch_trial_perf.exp_trials.might = get_correct_catch_trial_counts(exp_trials.might)
catch_trial_perf.all.might = rbind(catch_trial_perf.trials.might, catch_trial_perf.exp_trials.might) %>%
  group_by(workerid) %>%
  summarise(catch_perf = sum(catch_perf))




catch_trial_perf.exp_trials.probably = get_correct_catch_trial_counts(exp_trials.probably)
catch_trial_perf.trials.probably = get_correct_catch_trial_counts(trials.probably)
catch_trial_perf.all.probably = rbind(catch_trial_perf.trials.probably, catch_trial_perf.exp_trials.probably) %>%
  group_by(workerid) %>%
  summarise(catch_perf = sum(catch_perf))


exclude.might = catch_trial_perf.all.might %>%
  filter(catch_perf < EXCLUDE_BELOW) %>%
  .$workerid

exclude.probably = catch_trial_perf.all.probably %>%
  filter(catch_perf < EXCLUDE_BELOW) %>%
  .$workerid

print(paste("Excluded", length(exclude.might), "participants in might-biased condition."))
print(paste("Excluded", length(exclude.probably), "participants in probably-biased condition."))


#final data
d.might = trials.might %>% filter(., !(workerid %in% exclude.might))
d.probably = trials.probably %>% filter(., !(workerid %in% exclude.probably))

```

```{r perf_plot_1, fig.height=2,fig.width=10, echo=FALSE}

cutoff <- data.frame(yintercept=EXCLUDE_BELOW-0.5, cutoff=factor(EXCLUDE_BELOW-0.5))


ggplot(catch_trial_perf.all.probably, aes(x=factor(workerid), y=catch_perf)) + geom_bar(stat = "identity") + ggtitle("Catch trial performace in probably-biased cond.") + xlab ("participant") + ylab("correct responses") + geom_hline(aes(yintercept=yintercept, linetype=cutoff, color="red"), data=cutoff) + theme(legend.position="none")

```


```{r perf_plot_2, fig.height=2,fig.width=10, echo=FALSE}

ggplot(catch_trial_perf.all.might, aes(x=factor(workerid), y=catch_perf)) + geom_bar(stat = "identity") + ggtitle("Catch trial performace in might-biased cond.") + xlab ("participant") + ylab("correct responses") + geom_hline(aes(yintercept=yintercept, linetype=cutoff, color="red"), data=cutoff) + theme(legend.position="none")



```


### Aggregated results


```{r aggregate_plots, echo=FALSE, fig.width=10, fig.height=8}

plot_condition = function(d, plot_title) {
  drops <- c("modal1","rating1")
  d2 = d[ , !(names(d) %in% drops)]
  setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

  drops <- c("modal2","rating2")
  d3 = d[ , !(names(d) %in% drops)]
  setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

  drops <- c("modal2", "rating2", "modal1", "rating1")
  d4 = d[ , !(names(d) %in% drops)]
  d4$rating = d4$rating_other
  d4$modal = "other"

  d = rbind(d2, d3, d4)

  d$modal = factor(d$modal)
  d$percentage_blue_f = factor(d$percentage_blue)
  d_blue = d %>% filter(., grepl("blue", sentence2))
  d_orange = d %>% filter(., grepl("orange", sentence2))

  d_orange_reverse = d_orange
  d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

  d_comparison = rbind(d_blue, d_orange_reverse)
  d_comparison$blue= grepl("blue", d_comparison$sentence2)
  d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)

  p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +       geom_smooth(aes(col=modal,linetype=blue), method="loess") + ggtitle(plot_title) + xlab("percentage")

  p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(plot_title) + xlab("percentage")
  
  return(list("p1" = p1, "p2" = p2))

}



  ps1 = plot_condition(d.might, "might-biased")

  ps2 = plot_condition(d.probably, "probably-biased")

  
  grid.arrange(ps1$p1, ps1$p2, ps2$p1, ps2$p2, ncol=2, nrow=2)



```


### Aggregated results


```{r aggregate_plots_2, echo=FALSE, fig.width=10, fig.height=8}

plot_condition = function(d, plot_title) {
  drops <- c("modal1","rating1")
  d2 = d[ , !(names(d) %in% drops)]
  setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

  drops <- c("modal2","rating2")
  d3 = d[ , !(names(d) %in% drops)]
  setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

  drops <- c("modal2", "rating2", "modal1", "rating1")
  d4 = d[ , !(names(d) %in% drops)]
  d4$rating = d4$rating_other
  d4$modal = "other"

  d = rbind(d2, d3, d4)

  d$modal = factor(d$modal)
  d$percentage_blue_f = factor(d$percentage_blue)
  d_blue = d %>% filter(., grepl("blue", sentence2))
  d_orange = d %>% filter(., grepl("orange", sentence2))

  d_orange_reverse = d_orange
  d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

  d_comparison = rbind(d_blue, d_orange_reverse)
  d_comparison$blue= grepl("blue", d_comparison$sentence2)
  d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)

  p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +       geom_smooth(aes(col=modal,linetype=speaker_cond), method="loess") + ggtitle(plot_title) + xlab("percentage")

  p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(plot_title) + xlab("percentage")
  
  return(list("p1" = p1, "p2" = p2))

}



  ps1 = plot_condition(d.might, "might-biased")

  ps2 = plot_condition(d.probably, "probably-biased")

  
  grid.arrange(ps1$p1, ps1$p2, ps2$p1, ps2$p2, ncol=2, nrow=2)



aucs.all = rbind(aucs.might_f, aucs.probably_f, aucs.might_m, aucs.probably_m)

summary(lm(auc_diff ~ speaker * cond, data=aucs.all))

```
